--
-- Script was generated by Devart dbForge Studio for MySQL, Version 7.0.49.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 29/10/2016 11:02:12 a. m.
-- Server version: 5.7.11
-- Client version: 4.1
--


-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set default database
--
USE libopt;

--
-- Definition for table actividades
--
DROP TABLE IF EXISTS actividades;
CREATE TABLE actividades (
  id INT(11) NOT NULL AUTO_INCREMENT,
  grupo_id INT(11) NOT NULL,
  nombre_actividad VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 58
AVG_ROW_LENGTH = 4096
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table cargos
--
DROP TABLE IF EXISTS cargos;
CREATE TABLE cargos (
  id INT(11) NOT NULL AUTO_INCREMENT,
  nombre_cargo VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 12
AVG_ROW_LENGTH = 4096
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table grupo
--
DROP TABLE IF EXISTS grupo;
CREATE TABLE grupo (
  id INT(11) NOT NULL AUTO_INCREMENT,
  nombre_grupo VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 21
AVG_ROW_LENGTH = 2730
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table info
--
DROP TABLE IF EXISTS info;
CREATE TABLE info (
  id INT(11) NOT NULL AUTO_INCREMENT,
  month INT(11) NOT NULL,
  year INT(11) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 5
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table permissions
--
DROP TABLE IF EXISTS permissions;
CREATE TABLE permissions (
  id MEDIUMINT(8) NOT NULL AUTO_INCREMENT,
  name VARCHAR(12) NOT NULL,
  description TEXT NOT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX name (name)
)
ENGINE = INNODB
AUTO_INCREMENT = 6
AVG_ROW_LENGTH = 5461
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table pt
--
DROP TABLE IF EXISTS pt;
CREATE TABLE pt (
  id INT(11) NOT NULL AUTO_INCREMENT,
  user_id INT(11) NOT NULL,
  fecha DATE NOT NULL,
  hora VARCHAR(255) NOT NULL,
  actividad TEXT NOT NULL,
  tarea_superior BIT(1) DEFAULT NULL,
  parent_id INT(11) DEFAULT NULL,
  hora_fin VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 2902
AVG_ROW_LENGTH = 1024
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table rol
--
DROP TABLE IF EXISTS rol;
CREATE TABLE rol (
  id INT(11) NOT NULL AUTO_INCREMENT,
  rol VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 5
AVG_ROW_LENGTH = 5461
CHARACTER SET utf8
COLLATE utf8_spanish_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table systema
--
DROP TABLE IF EXISTS systema;
CREATE TABLE systema (
  id INT(11) NOT NULL AUTO_INCREMENT,
  cod VARCHAR(655) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table temppt
--
DROP TABLE IF EXISTS temppt;
CREATE TABLE temppt (
  id INT(11) NOT NULL AUTO_INCREMENT,
  user_id INT(11) NOT NULL,
  fecha DATE NOT NULL,
  hora VARCHAR(255) NOT NULL,
  actividad TEXT NOT NULL,
  tarea_superior BIT(1) DEFAULT NULL,
  parent_id INT(11) DEFAULT NULL,
  hora_fin VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 159
AVG_ROW_LENGTH = 1024
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table users_meta
--
DROP TABLE IF EXISTS users_meta;
CREATE TABLE users_meta (
  user_id MEDIUMINT(8) NOT NULL,
  name VARCHAR(40) NOT NULL,
  value VARCHAR(255) NOT NULL,
  INDEX name (name),
  INDEX user_id (user_id),
  CONSTRAINT users_meta_ibfk_1 FOREIGN KEY (user_id)
    REFERENCES myshop.users(id) ON DELETE CASCADE ON UPDATE NO ACTION
)
ENGINE = INNODB
AVG_ROW_LENGTH = 5461
CHARACTER SET latin1
COLLATE latin1_swedish_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table version
--
DROP TABLE IF EXISTS version;
CREATE TABLE version (
  id INT(11) NOT NULL AUTO_INCREMENT,
  version VARCHAR(255) NOT NULL,
  fecha DATE DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 8192
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table users
--
DROP TABLE IF EXISTS users;
CREATE TABLE users (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(80) NOT NULL,
  email VARCHAR(30) DEFAULT NULL,
  cargo INT(11) DEFAULT NULL,
  password VARCHAR(60) NOT NULL,
  rol_id INT(11) DEFAULT NULL,
  parent_id INT(11) DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT FK_users_cargos_id FOREIGN KEY (cargo)
    REFERENCES cargos(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_users_rol_id FOREIGN KEY (rol_id)
    REFERENCES rol(id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 30
AVG_ROW_LENGTH = 8192
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table users_permissions
--
DROP TABLE IF EXISTS users_permissions;
CREATE TABLE users_permissions (
  user_id MEDIUMINT(8) NOT NULL,
  permission_id MEDIUMINT(8) NOT NULL,
  INDEX users_permissions_ibfk_1 (user_id),
  CONSTRAINT users_permissions_ibfk_2 FOREIGN KEY (permission_id)
    REFERENCES permissions(id) ON DELETE CASCADE ON UPDATE NO ACTION
)
ENGINE = INNODB
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table analisis
--
DROP TABLE IF EXISTS analisis;
CREATE TABLE analisis (
  id INT(11) NOT NULL AUTO_INCREMENT,
  users_id INT(11) DEFAULT NULL,
  mes VARCHAR(255) DEFAULT NULL,
  ano VARCHAR(255) DEFAULT NULL,
  analisis TEXT DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT FK_analisis_users_id FOREIGN KEY (users_id)
    REFERENCES users(id) ON DELETE CASCADE ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 9
AVG_ROW_LENGTH = 8192
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table aprobacionpt
--
DROP TABLE IF EXISTS aprobacionpt;
CREATE TABLE aprobacionpt (
  id INT(11) NOT NULL AUTO_INCREMENT,
  users_id INT(11) NOT NULL,
  month INT(11) NOT NULL,
  year INT(11) DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT FK_aprobacionpt_users_id FOREIGN KEY (users_id)
    REFERENCES users(id) ON DELETE CASCADE ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 20
AVG_ROW_LENGTH = 5461
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table nuevas_tareas
--
DROP TABLE IF EXISTS nuevas_tareas;
CREATE TABLE nuevas_tareas (
  id INT(11) NOT NULL AUTO_INCREMENT,
  users_id INT(11) DEFAULT NULL,
  nuevatarea VARCHAR(255) DEFAULT NULL,
  quien_origino VARCHAR(255) DEFAULT NULL,
  causas VARCHAR(455) DEFAULT NULL,
  mes VARCHAR(255) DEFAULT NULL,
  ano VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT FK_nuevas_tareas_users_id FOREIGN KEY (users_id)
    REFERENCES users(id) ON DELETE CASCADE ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 3
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table predate
--
DROP TABLE IF EXISTS predate;
CREATE TABLE predate (
  id INT(11) NOT NULL AUTO_INCREMENT,
  user_id INT(11) DEFAULT NULL,
  fecha DATE DEFAULT NULL,
  hora_inicio VARCHAR(255) DEFAULT NULL,
  hora_fin VARCHAR(255) DEFAULT NULL,
  actividad VARCHAR(355) DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT FK_predate_users_id FOREIGN KEY (user_id)
    REFERENCES users(id) ON DELETE CASCADE ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 6
AVG_ROW_LENGTH = 4096
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table predefinida_fecha
--
DROP TABLE IF EXISTS predefinida_fecha;
CREATE TABLE predefinida_fecha (
  id INT(11) NOT NULL AUTO_INCREMENT,
  tarea VARCHAR(555) DEFAULT NULL,
  dia INT(11) DEFAULT NULL,
  hora VARCHAR(255) DEFAULT NULL,
  users_id INT(11) DEFAULT NULL,
  hora_fin VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT FK_predefinida_fecha_users_id FOREIGN KEY (users_id)
    REFERENCES users(id) ON DELETE CASCADE ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 10
AVG_ROW_LENGTH = 8192
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table predefinidas
--
DROP TABLE IF EXISTS predefinidas;
CREATE TABLE predefinidas (
  id INT(11) NOT NULL AUTO_INCREMENT,
  tarea VARCHAR(455) DEFAULT NULL,
  dia VARCHAR(255) DEFAULT NULL,
  hora VARCHAR(255) DEFAULT NULL,
  hora_fin VARCHAR(255) DEFAULT NULL,
  users_id INT(11) DEFAULT NULL,
  orden INT(11) DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT FK_predefinidas_users_id FOREIGN KEY (users_id)
    REFERENCES users(id) ON DELETE CASCADE ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 68
AVG_ROW_LENGTH = 2340
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table predefinidas_dias_fecha
--
DROP TABLE IF EXISTS predefinidas_dias_fecha;
CREATE TABLE predefinidas_dias_fecha (
  id INT(11) NOT NULL AUTO_INCREMENT,
  tarea VARCHAR(555) DEFAULT NULL,
  cuando INT(11) DEFAULT NULL,
  dia VARCHAR(255) DEFAULT NULL,
  hora VARCHAR(255) DEFAULT NULL,
  users_id INT(11) DEFAULT NULL,
  orden INT(11) DEFAULT NULL,
  hora_fin VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT FK_predefinidas_dias_fecha_users_id FOREIGN KEY (users_id)
    REFERENCES users(id) ON DELETE CASCADE ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 12
AVG_ROW_LENGTH = 4096
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table tareas_incumplidas
--
DROP TABLE IF EXISTS tareas_incumplidas;
CREATE TABLE tareas_incumplidas (
  id INT(11) NOT NULL AUTO_INCREMENT,
  users_id INT(11) DEFAULT NULL,
  pt_id INT(11) DEFAULT NULL,
  quien_origino VARCHAR(255) DEFAULT NULL,
  causas VARCHAR(455) DEFAULT NULL,
  incumplida BIT(1) DEFAULT NULL,
  suspendida BIT(1) DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT FK_tareas_incumplidas_pt_id FOREIGN KEY (pt_id)
    REFERENCES pt(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_tareas_incumplidas_users_id FOREIGN KEY (users_id)
    REFERENCES users(id) ON DELETE CASCADE ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table tareasprincipales
--
DROP TABLE IF EXISTS tareasprincipales;
CREATE TABLE tareasprincipales (
  id INT(11) NOT NULL AUTO_INCREMENT,
  users_id INT(11) DEFAULT NULL,
  tarea VARCHAR(255) DEFAULT NULL,
  mes INT(11) DEFAULT NULL,
  ano INT(11) DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT FK_tareasprincipales_users_id FOREIGN KEY (users_id)
    REFERENCES users(id) ON DELETE CASCADE ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 18
AVG_ROW_LENGTH = 4096
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table vacaciones
--
DROP TABLE IF EXISTS vacaciones;
CREATE TABLE vacaciones (
  id INT(11) NOT NULL AUTO_INCREMENT,
  users_id INT(11) NOT NULL,
  desde DATE NOT NULL,
  hasta DATE NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT FK_vacaciones_users_id FOREIGN KEY (users_id)
    REFERENCES users(id) ON DELETE CASCADE ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 4
AVG_ROW_LENGTH = 4096
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table predate_subor
--
DROP TABLE IF EXISTS predate_subor;
CREATE TABLE predate_subor (
  id INT(11) NOT NULL AUTO_INCREMENT,
  predate_id INT(11) NOT NULL,
  user_id INT(11) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT FK_predate_subor_predate_id FOREIGN KEY (predate_id)
    REFERENCES predate(id) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT FK_predate_subor_users_id FOREIGN KEY (user_id)
    REFERENCES users(id) ON DELETE CASCADE ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 17
AVG_ROW_LENGTH = 1024
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table predefinida_fecha_subor
--
DROP TABLE IF EXISTS predefinida_fecha_subor;
CREATE TABLE predefinida_fecha_subor (
  id INT(11) NOT NULL AUTO_INCREMENT,
  predefinida_fecha_id INT(11) NOT NULL,
  user_id INT(11) DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT FK_predefinida_fecha_subor_predefinida_fecha_id FOREIGN KEY (predefinida_fecha_id)
    REFERENCES predefinida_fecha(id) ON DELETE CASCADE ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 5
AVG_ROW_LENGTH = 5461
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table predefinidas_dias_fecha_subor
--
DROP TABLE IF EXISTS predefinidas_dias_fecha_subor;
CREATE TABLE predefinidas_dias_fecha_subor (
  id INT(11) NOT NULL AUTO_INCREMENT,
  predefinidas_dias_fecha_id INT(11) NOT NULL,
  user_id INT(11) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT FK_predefinidas_dias_fecha_subor_predefinidas_dias_fecha_id FOREIGN KEY (predefinidas_dias_fecha_id)
    REFERENCES predefinidas_dias_fecha(id) ON DELETE CASCADE ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 7
AVG_ROW_LENGTH = 2730
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table predefinidas_subor
--
DROP TABLE IF EXISTS predefinidas_subor;
CREATE TABLE predefinidas_subor (
  id INT(11) NOT NULL AUTO_INCREMENT,
  predefinidas_id INT(11) NOT NULL,
  users_id INT(11) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT FK_predefinidas_subor_predefinidas_id FOREIGN KEY (predefinidas_id)
    REFERENCES predefinidas(id) ON DELETE CASCADE ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 13
AVG_ROW_LENGTH = 3276
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table tareas_suspendidas
--
DROP TABLE IF EXISTS tareas_suspendidas;
CREATE TABLE tareas_suspendidas (
  id INT(11) NOT NULL AUTO_INCREMENT,
  cumplimiento_id INT(11) DEFAULT NULL,
  tarea VARCHAR(255) DEFAULT NULL,
  quien_origino VARCHAR(255) DEFAULT NULL,
  causas VARCHAR(455) DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT FK_tareas_suspendidas_cumplimiento_id FOREIGN KEY (cumplimiento_id)
    REFERENCES analisis(id) ON DELETE CASCADE ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

-- 
-- Dumping data for table actividades
--
INSERT INTO actividades VALUES
(1, 1, 'Matutino'),
(2, 1, 'Puntualizacion'),
(3, 1, 'Trabajo Voluntario'),
(4, 2, 'Revision de Expedientes'),
(5, 4, 'Atencion a Reportes'),
(6, 6, 'Preparaci�n de Reservas de Cuadro'),
(7, 2, 'Calidad'),
(8, 6, 'Chequeo de Inversiones del MINTUR'),
(9, 6, 'Despacho con JB Softur'),
(10, 6, 'Despacho con JB AT&C+'),
(11, 6, 'Despacho con Esp. Comercial'),
(12, 6, 'Despacho con Esp. RRHH'),
(13, 6, 'Despacho con Esp. Economica (EP)'),
(14, 6, 'Consejo de Direcci�n del MINTUR'),
(15, 6, 'Consejo de Direccion Ampliado de GET'),
(16, 6, 'Despacho con Director General de GET'),
(17, 6, 'Consejo de Direccion UEB'),
(18, 6, 'Comite de Prevencion y Control UEB'),
(19, 16, 'Revisi�n y Aprobaci�n de Planes de Trabajo'),
(20, 6, 'Evaluacion de desempe�o de subordinados'),
(21, 16, 'Elaboracion y entrega de Plan de Trabajo y cumplimiento del mes anterior'),
(22, 17, 'Envio de los Anexos del Procedimiento de Internet a Clientes'),
(23, 6, 'Elaboraci�n y envio de Informaci�n de Mantenimiento'),
(24, 6, 'Verificar entrega de parte comercial'),
(25, 19, 'Elaboraci�n y envio de parte comercial'),
(26, 12, 'Elaboraci�n, revision y envio de Informaci�n de Transporte'),
(27, 12, 'Elaboracion y envio de plan de transportacion de mes proximo'),
(28, 6, 'Envio de Certifico de las acciones de Control Externas recibidas por la UEB'),
(29, 1, 'Autopreparaci�n'),
(30, 12, 'Viaje hacia la Habana'),
(31, 12, 'Retorno desde la Habana'),
(32, 1, 'Trabajo en GET Habana'),
(33, 1, 'Feriado'),
(34, 1, 'Dia de la Rebeldia Nacional'),
(35, 1, 'Dia Internacional de los Trabajadores'),
(36, 6, 'Atenci�n al cierre de mes'),
(37, 1, 'Elaboraci�n, Revisi�n y Aprobaci�n de Planes de trabajo'),
(38, 18, 'Elaboracion, revision y envio de informacion de Mantenimiento'),
(39, 1, 'VACACIONES'),
(40, 14, 'Analisis de Trazas'),
(41, 14, 'Elaboraci�n,revisi�n y/o actualizaci�n de Planes de Seguridad Inform�tica'),
(42, 20, 'Trabajo en Taller'),
(43, 14, 'Revisi�n de Tarea Enlace'),
(44, 6, 'Recorrido por Clientes y Proveedores de Moron'),
(45, 6, 'Recorrido por Clientes y Proveedores de Ciego de Avila'),
(46, 6, 'Recorrido por Clientes y Proveedores de los Cayos.'),
(47, 6, 'Revision de Informe Econ�mico'),
(48, 6, 'Control a la actividad de Softur'),
(49, 6, 'Control a la actividad de AT&C+'),
(50, 6, 'Visita a Clientes de Sancti Spiritus'),
(51, 3, 'Trabajo en el cierre de mes'),
(52, 3, 'Contabilizaci�n de operaciones diarias'),
(53, 3, 'Confecci�n y env�o de informaciones a la Empresa'),
(54, 3, 'Pagos a la ONAT y Retenciones en BPA'),
(56, 3, 'Confecci�n de pagos a proveedores'),
(57, 3, 'Cierre del sistema mistral y conteo del 10% de inventarios del almac�n');

-- 
-- Dumping data for table cargos
--
INSERT INTO cargos VALUES
(1, 'Director UEB GET Ciego de Avilaa'),
(2, 'Especialista B en Ciencias Inform�ticas'),
(3, 'Especialista C en Gesti�n Econ�mica'),
(4, 'Especialista B en Gesti�n de Recursos Humanos'),
(5, 'Especialista B en Ciencias Inform�ticas (JB)'),
(6, 'Especialista C en Ciencias Inform�ticas'),
(7, 'Especialista C en Gesti�n Econ�mica (EP)'),
(8, 'Especialista C en Gesti�n Comercial'),
(9, 'Especialista General en Tecnolog�a de las Comunicaciones, la Electr�nica, la Autom�tica y los Servicios T�cnicos'),
(10, 'Especialista General en Tecnolog�a de las Comunicaciones, la Electr�nica, la Autom�tica y los Servicios T�cnicos (JB)'),
(11, 'Director General de GET');

-- 
-- Dumping data for table grupo
--
INSERT INTO grupo VALUES
(1, 'Actividades Generales'),
(2, 'RRHH'),
(3, 'Economia'),
(4, 'Software'),
(5, 'Hardware'),
(6, 'Direcci�n'),
(7, 'Calidad'),
(8, 'Defensa'),
(9, 'Control Interno'),
(10, 'Contrataci�n'),
(11, 'Facturaci�n'),
(12, 'Transporte'),
(13, 'Almacen'),
(14, 'Seguridad Inform�tica'),
(16, 'Organizaci�n'),
(17, 'Internet a Clientes'),
(18, 'Mantenimiento'),
(19, 'Comercial'),
(20, 'AT&C+');

-- 
-- Dumping data for table info
--
INSERT INTO info VALUES
(1, 9, 2016),
(2, 10, 2016),
(3, 8, 2016),
(4, 11, 2016);

-- 
-- Dumping data for table permissions
--
INSERT INTO permissions VALUES
(4, 'admin', 'Administrador'),
(5, 'user', 'Usuario');

-- 
-- Dumping data for table pt
--
INSERT INTO pt VALUES
(2875, 17, '2016-10-01', 'T/D', 'VACACIONES', False, NULL, 'T/D'),
(2876, 17, '2016-10-02', 'T/D', 'VACACIONES', False, NULL, 'T/D'),
(2877, 17, '2016-10-03', 'T/D', 'VACACIONES', False, NULL, 'T/D'),
(2878, 17, '2016-10-04', 'T/D', 'VACACIONES', False, NULL, 'T/D'),
(2879, 17, '2016-10-05', 'T/D', 'VACACIONES', False, NULL, 'T/D'),
(2880, 17, '2016-10-06', 'T/D', 'VACACIONES', False, NULL, 'T/D'),
(2881, 17, '2016-10-07', 'T/D', 'VACACIONES', False, NULL, 'T/D'),
(2882, 17, '2016-10-08', 'T/D', 'VACACIONES', False, NULL, 'T/D'),
(2883, 17, '2016-10-10', '08:15', 'Matutino', NULL, NULL, '08:40'),
(2884, 17, '2016-10-10', '08:30', 'Reuni�n de Puntualizaci�n', NULL, NULL, '09:00'),
(2885, 17, '2016-10-13', '14:00', 'Verificar entrega de parte Comercial', NULL, NULL, '14:30'),
(2886, 17, '2016-10-17', '08:15', 'Matutino', NULL, NULL, '08:40'),
(2887, 17, '2016-10-17', '08:30', 'Reuni�n de Puntualizaci�n', NULL, NULL, '09:00'),
(2888, 17, '2016-10-20', '14:00', 'Verificar entrega de parte Comercial', NULL, NULL, NULL),
(2889, 17, '2016-10-24', '08:15', 'Matutino', NULL, NULL, '08:40'),
(2890, 17, '2016-10-24', '08:30', 'Reuni�n de Puntualizaci�n', NULL, NULL, '09:00'),
(2891, 17, '2016-10-27', '14:00', 'Verificar entrega de parte Comercial', NULL, NULL, NULL),
(2892, 17, '2016-10-31', '08:15', 'Matutino', NULL, NULL, '08:40'),
(2893, 17, '2016-10-31', '08:30', 'Reuni�n de Puntualizaci�n', NULL, NULL, '09:00'),
(2894, 17, '2016-10-10', '09:00', 'Consejo de Direccion UEB', NULL, NULL, '09:30'),
(2895, 17, '2016-10-10', '15:00', 'Reunion del Nucleo del PCC', NULL, NULL, '15:30'),
(2896, 17, '2016-10-17', '14:00', 'Comite de Prevencion y Control UEB', NULL, NULL, '14:30'),
(2897, 17, '2016-10-12', '14:00', 'Trabajo con tareas anuales', False, NULL, '14:00'),
(2898, 17, '2016-10-14', '14:00', 'Autopreparaci�n', False, NULL, '15:00'),
(2899, 17, '2016-10-12', '08:00', 'probando slider', False, NULL, '08:30'),
(2900, 17, '2016-10-13', '08:00', 'probando slider', False, 17, '08:30'),
(2901, 17, '2016-10-14', '08:00', 'probando slider', False, 17, '08:30');

-- 
-- Dumping data for table rol
--
INSERT INTO rol VALUES
(1, 'Administrador'),
(2, 'Usuario'),
(3, 'Directivo'),
(4, 'Supremo');

-- 
-- Dumping data for table systema
--
INSERT INTO systema VALUES
(1, 'Y/tn8MdKK8Pdu5iSkyGBJUxrIcSB6+RdN5mPdELilzMaOdbQCZwKGOBNelhuRxd6f184+RptJmcphfBxle0WGg==');

-- 
-- Dumping data for table temppt
--
INSERT INTO temppt VALUES
(2, 18, '2016-08-08', '09:30', 'Consejo de Direccion UEB', True, 17, NULL),
(3, 23, '2016-08-08', '09:30', 'Consejo de Direccion UEB', True, 17, NULL),
(4, 13, '2016-08-08', '09:30', 'Consejo de Direccion UEB', True, 17, NULL),
(5, 16, '2016-08-08', '09:30', 'Consejo de Direccion UEB', True, 17, NULL),
(6, 25, '2016-08-08', '09:30', 'Consejo de Direccion UEB', True, 17, NULL),
(7, 25, '2016-08-04', '10:00', 'Despacho con Esp. Comercial', True, 17, NULL),
(8, 18, '2016-08-05', '15:00', 'Despacho con Esp. Economica (EP)', True, 17, NULL),
(9, 18, '2016-08-08', '17:00', 'Preparaci�n de Reservas de Cuadro', True, 17, NULL),
(10, 23, '2016-08-08', '17:00', 'Preparaci�n de Reservas de Cuadro', True, 17, NULL),
(11, 13, '2016-08-08', '17:00', 'Preparaci�n de Reservas de Cuadro', True, 17, NULL),
(14, 24, '2016-08-08', '17:00', 'Preparaci�n de Reservas de Cuadro', True, 17, NULL),
(15, 24, '2016-08-09', '10:00', 'Elaboracion, revision y envio de informacion de Mantenimiento', True, 17, NULL),
(16, 13, '2016-08-09', '15:00', 'Envio de los Anexos del Procedimiento de Internet a Clientes', True, 17, NULL),
(17, 16, '2016-08-09', '16:00', 'Despacho con Esp. RRHH', True, 17, NULL),
(18, 18, '2016-08-08', '17:00', 'Reunion del Nucleo del PCC', True, 17, NULL),
(19, 23, '2016-08-08', '17:00', 'Reunion del Nucleo del PCC', True, 17, NULL),
(20, 13, '2016-08-08', '17:00', 'Reunion del Nucleo del PCC', True, 17, NULL),
(23, 24, '2016-08-08', '17:00', 'Reunion del Nucleo del PCC', True, 17, NULL),
(24, 16, '2016-08-17', '09:00', 'Despacho con Esp. RRHH', True, 17, NULL),
(26, 18, '2016-08-22', '10:00', 'Comite de Prevencion y Control UEB', True, 17, NULL),
(27, 23, '2016-08-22', '10:00', 'Comite de Prevencion y Control UEB', True, 17, NULL),
(29, 16, '2016-08-22', '10:00', 'Comite de Prevencion y Control UEB', True, 17, NULL),
(30, 25, '2016-08-22', '10:00', 'Comite de Prevencion y Control UEB', True, 17, NULL),
(31, 16, '2016-08-22', '15:00', 'Preparaci�n de Reservas de Cuadro', True, 17, NULL),
(33, 23, '2016-08-26', 'T/D', 'Control a la actividad de Hardware', True, 17, NULL),
(34, 26, '2016-08-26', 'T/D', 'Control a la actividad de Hardware', True, 17, NULL),
(35, 28, '2016-08-26', 'T/D', 'Control a la actividad de Hardware', True, 17, NULL),
(36, 29, '2016-08-26', 'T/D', 'Control a la actividad de Hardware', True, 17, NULL),
(38, 18, '2016-08-01', '08:15', 'Matutino', True, 17, NULL),
(39, 23, '2016-08-01', '08:15', 'Matutino', True, 17, NULL),
(40, 13, '2016-08-01', '08:15', 'Matutino', True, 17, NULL),
(41, 14, '2016-08-01', '08:15', 'Matutino', True, 17, NULL),
(44, 16, '2016-08-01', '08:15', 'Matutino', True, 17, NULL),
(45, 24, '2016-08-01', '08:15', 'Matutino', True, 17, NULL),
(46, 25, '2016-08-01', '08:15', 'Matutino', True, 17, NULL),
(47, 26, '2016-08-01', '08:15', 'Matutino', True, 17, NULL),
(48, 28, '2016-08-01', '08:15', 'Matutino', True, 17, NULL),
(49, 29, '2016-08-01', '08:15', 'Matutino', True, 17, NULL),
(51, 18, '2016-08-01', '09:00', 'Reuni�n de Puntualizaci�n', True, 17, NULL),
(52, 23, '2016-08-01', '09:00', 'Reuni�n de Puntualizaci�n', True, 17, NULL),
(53, 25, '2016-08-01', '09:00', 'Reuni�n de Puntualizaci�n', True, 17, NULL),
(55, 23, '2016-08-01', '15:00', 'Despacho con JB AT&C+', True, 17, NULL),
(57, 18, '2016-08-08', '08:15', 'Matutino', True, 17, NULL),
(58, 23, '2016-08-08', '08:15', 'Matutino', True, 17, NULL),
(59, 13, '2016-08-08', '08:15', 'Matutino', True, 17, NULL),
(60, 14, '2016-08-08', '08:15', 'Matutino', True, 17, NULL),
(63, 16, '2016-08-08', '08:15', 'Matutino', True, 17, NULL),
(64, 24, '2016-08-08', '08:15', 'Matutino', True, 17, NULL),
(65, 25, '2016-08-08', '08:15', 'Matutino', True, 17, NULL),
(66, 26, '2016-08-08', '08:15', 'Matutino', True, 17, NULL),
(67, 28, '2016-08-08', '08:15', 'Matutino', True, 17, NULL),
(68, 29, '2016-08-08', '08:15', 'Matutino', True, 17, NULL),
(70, 18, '2016-08-08', '09:00', 'Reuni�n de Puntualizaci�n', True, 17, NULL),
(71, 23, '2016-08-08', '09:00', 'Reuni�n de Puntualizaci�n', True, 17, NULL),
(72, 25, '2016-08-08', '09:00', 'Reuni�n de Puntualizaci�n', True, 17, NULL),
(74, 18, '2016-08-22', '08:15', 'Matutino', True, 17, NULL),
(75, 23, '2016-08-22', '08:15', 'Matutino', True, 17, NULL),
(76, 13, '2016-08-22', '08:15', 'Matutino', True, 17, NULL),
(77, 14, '2016-08-22', '08:15', 'Matutino', True, 17, NULL),
(80, 16, '2016-08-22', '08:15', 'Matutino', True, 17, NULL),
(81, 24, '2016-08-22', '08:15', 'Matutino', True, 17, NULL),
(82, 25, '2016-08-22', '08:15', 'Matutino', True, 17, NULL),
(83, 26, '2016-08-22', '08:15', 'Matutino', True, 17, NULL),
(84, 28, '2016-08-22', '08:15', 'Matutino', True, 17, NULL),
(85, 29, '2016-08-22', '08:15', 'Matutino', True, 17, NULL),
(87, 18, '2016-08-22', '09:00', 'Reuni�n de Puntualizaci�n', True, 17, NULL),
(88, 23, '2016-08-22', '09:00', 'Reuni�n de Puntualizaci�n', True, 17, NULL),
(89, 25, '2016-08-22', '09:00', 'Reuni�n de Puntualizaci�n', True, 17, NULL),
(91, 18, '2016-08-29', '08:15', 'Matutino', True, 17, NULL),
(92, 23, '2016-08-29', '08:15', 'Matutino', True, 17, NULL),
(93, 13, '2016-08-29', '08:15', 'Matutino', True, 17, NULL),
(94, 14, '2016-08-29', '08:15', 'Matutino', True, 17, NULL),
(97, 16, '2016-08-29', '08:15', 'Matutino', True, 17, NULL),
(98, 24, '2016-08-29', '08:15', 'Matutino', True, 17, NULL),
(99, 25, '2016-08-29', '08:15', 'Matutino', True, 17, NULL),
(100, 26, '2016-08-29', '08:15', 'Matutino', True, 17, NULL),
(101, 28, '2016-08-29', '08:15', 'Matutino', True, 17, NULL),
(102, 29, '2016-08-29', '08:15', 'Matutino', True, 17, NULL),
(104, 18, '2016-08-29', '09:00', 'Reuni�n de Puntualizaci�n', True, 17, NULL),
(105, 23, '2016-08-29', '09:00', 'Reuni�n de Puntualizaci�n', True, 17, NULL),
(106, 25, '2016-08-29', '09:00', 'Reuni�n de Puntualizaci�n', True, 17, NULL),
(107, 18, '2016-08-24', '09:00', 'Despacho con Esp. Economica (EP)', True, 17, NULL),
(108, 13, '2016-08-01', '08:15', 'Matutino', True, 15, NULL),
(109, 14, '2016-08-01', '08:15', 'Matutino', True, 15, NULL),
(110, 15, '2016-09-08', '09:00', 'Reuni�n de Preparaci�n de Control del MINCOM al MINTUR.', True, 17, NULL),
(111, 27, '2016-09-08', '09:00', 'Reuni�n de Preparaci�n de Control del MINCOM al MINTUR.', True, 17, NULL),
(112, 25, '2016-09-09', '10:00', 'Despacho con Esp. Comercial', True, 17, NULL),
(113, 24, '2016-09-09', '14:00', 'Elaboraci�n y envio de Informaci�n de Mantenimiento', True, 17, NULL),
(114, 13, '2016-09-09', '15:00', 'Envio de los Anexos del Procedimiento de Internet a Clientes', True, 17, NULL),
(115, 15, '2016-09-12', '08:30', 'Reuni�n de Puntualizaci�n', True, 17, NULL),
(116, 18, '2016-09-12', '08:30', 'Reuni�n de Puntualizaci�n', True, 17, NULL),
(117, 23, '2016-09-12', '08:30', 'Reuni�n de Puntualizaci�n', True, 17, NULL),
(118, 13, '2016-09-13', 'T/D', 'Recorrido por Clientes y Proveedores de los Cayos.', True, 17, NULL),
(119, 24, '2016-09-13', 'T/D', 'Recorrido por Clientes y Proveedores de los Cayos.', True, 17, NULL),
(120, 13, '2016-09-14', 'T/D', 'Recorrido por Clientes y Proveedores de los Cayos.', True, 17, NULL),
(121, 24, '2016-09-14', 'T/D', 'Recorrido por Clientes y Proveedores de los Cayos.', True, 17, NULL),
(122, 16, '2016-09-15', '09:00', 'Despacho con Esp. RRHH', True, 17, NULL),
(123, 15, '2016-09-19', 'T/D', 'Atenci�n de Control Estatal del MINCOM ', True, 17, NULL),
(124, 13, '2016-09-19', 'T/D', 'Atenci�n de Control Estatal del MINCOM ', True, 17, NULL),
(125, 27, '2016-09-19', 'T/D', 'Atenci�n de Control Estatal del MINCOM ', True, 17, NULL),
(126, 16, '2016-09-19', 'T/D', 'Atenci�n de Control Estatal del MINCOM ', True, 17, NULL),
(127, 15, '2016-09-20', 'T/D', 'Atenci�n de Control Estatal del MINCOM ', True, 17, NULL),
(128, 13, '2016-09-20', 'T/D', 'Atenci�n de Control Estatal del MINCOM ', True, 17, NULL),
(129, 27, '2016-09-20', 'T/D', 'Atenci�n de Control Estatal del MINCOM ', True, 17, NULL),
(130, 16, '2016-09-20', 'T/D', 'Atenci�n de Control Estatal del MINCOM ', True, 17, NULL),
(131, 15, '2016-09-21', '13:00', 'Control a la actividad de Softur', True, 17, NULL),
(132, 16, '2016-09-21', '13:00', 'Control a la actividad de Softur', True, 17, NULL),
(133, 16, '2016-09-23', 'T/D', 'Control a la actividad de AT&C+', True, 17, NULL),
(134, 15, '2016-09-26', '10:00', 'Comite de Prevencion y Control UEB', True, 17, NULL),
(135, 18, '2016-09-26', '10:00', 'Comite de Prevencion y Control UEB', True, 17, NULL),
(136, 23, '2016-09-26', '10:00', 'Comite de Prevencion y Control UEB', True, 17, NULL),
(137, 27, '2016-09-26', '10:00', 'Comite de Prevencion y Control UEB', True, 17, NULL),
(138, 16, '2016-09-26', '10:00', 'Comite de Prevencion y Control UEB', True, 17, NULL),
(139, 25, '2016-09-26', '10:00', 'Comite de Prevencion y Control UEB', True, 17, NULL),
(140, 16, '2016-09-26', '15:00', 'Preparaci�n de Reservas de Cuadro', True, 17, NULL),
(141, 15, '2016-09-27', 'T/D', 'Visita a Clientes de Sancti Spiritus', True, 17, NULL),
(142, 18, '2016-09-28', '09:00', 'Despacho con Esp. Economica (EP)', True, 17, NULL),
(143, 15, '2016-09-30', '16:00', 'Revisi�n y Aprobaci�n de Planes de Trabajo', True, 17, NULL),
(144, 18, '2016-09-30', '16:00', 'Revisi�n y Aprobaci�n de Planes de Trabajo', True, 17, NULL),
(145, 23, '2016-09-30', '16:00', 'Revisi�n y Aprobaci�n de Planes de Trabajo', True, 17, NULL),
(146, 15, '2016-09-30', '17:00', 'Evaluacion de desempe�o de subordinados', True, 17, NULL),
(147, 18, '2016-09-30', '17:00', 'Evaluacion de desempe�o de subordinados', True, 17, NULL),
(148, 23, '2016-09-30', '17:00', 'Evaluacion de desempe�o de subordinados', True, 17, NULL),
(149, 23, '2016-09-23', 'T/D', 'Control a la actividad de AT&C+', True, 17, NULL),
(150, 3, '2016-09-01', '11:00', 'Tarea para michel', True, 15, '11:30'),
(151, 3, '2016-09-01', '12:00', 'Almuerzo Especial', True, 17, '13:00'),
(152, 15, '2016-10-14', '14:00', 'Autopreparaci�n', True, 17, '15:00'),
(153, 3, '2016-10-14', '14:00', 'Autopreparaci�n', True, 17, '15:00'),
(154, 25, '2016-10-13', '14:00', 'Verificar entrega de parte Comercial', True, 17, '14:30'),
(155, 3, '2016-10-08', '08:00', 'Autopreparaci�n', True, 17, '08:30'),
(156, 3, '2016-10-12', '08:00', 'probando slider', True, 17, '08:30'),
(157, 3, '2016-10-13', '08:00', 'probando slider', True, 17, '08:30'),
(158, 3, '2016-10-14', '08:00', 'probando slider', True, 17, '08:30');

-- 
-- Dumping data for table users_meta
--

-- Table zunpt.users_meta does not contain any data (it is empty)

-- 
-- Dumping data for table version
--
INSERT INTO version VALUES
(1, '1.5', '2016-10-05');

-- 
-- Dumping data for table users
--
INSERT INTO users VALUES
(3, 'Michel Lozada Montano', 'michellm@get.mrn.tur.cu', 2, 'mAe14gM74si46szDtEV5Lc77aGASP56lTlb8CfY1+Jk=', 1, 15),
(13, 'Ricardo Pico Ochandategui', 'ricardo.pico@get.mrn.tur.cu', 1, 'ZkFPbJQiMptJQ6ZHRYi0pauefS84HHa8teLyQZjgMjg=', 2, 15),
(14, 'Rene L�pez Marrero', 'rene@get.mrn.tur.cu', 1, 'z3isKChQPAKN9TKe+JU1mLNS1kRjNqXP/5dQDLVbNis=', 2, 15),
(15, 'Alain Varela Martin', 'alainv@get.mrn.tur.cu', 1, 'cSwQ4Pp8nQFkfq+Zb/ghEnEFJGz2HiNbof2mDckhwSA=', 3, 17),
(16, 'Marleny Cruz Perez', 'marleny@get.mrn.tur.cu', 1, 'EUGe6deIVG+zpqF2g+iiP+YWAvMqJZ0KOp+ygbwn0n4=', 1, 18),
(17, 'Amaury Basulto Sobrado', 'director@get.mrn.tur.cu', 1, 'eRzuW8+Pov9IbPaRv2UvGsK9zHnRYt/ZfIwA1wBhTYE=', 3, 0),
(18, 'Rosamary Padron', 'jeconomica@get.mrn.tur.cu', 1, 'jKvfytk2kTJj6Fy30kVAqNOxetsDVk96lhVjMdVZQpk=', 3, 17),
(20, 'Administrador', 'admin@admin.com', 1, 'gSAZ3on74YHaWJZbHyNFIcyl91Aj3ev4Aev4I3m8qnM=', 1, 0),
(21, 'Evelio Gonz�lez Fornaris', 'director@get.tur.cu', 1, 'iIP1iP+U2XGf5+bs6K3f402FJoktLM+wUI2uepvINXo=', 4, 0),
(22, 'H�ctor Trujillo Bernal', 'hector.trujillo@get.mrn.tur.cu', 1, 'Y54XiUTFQYJS1CDSlfzCJB/5Cz4fezAD4N2hzCcfVjs=', 2, 15),
(23, 'Janled Menegia Gonzalez', 'janled.menegia@get.mrn.tur.cu', 1, 'TK8Ij3MgiGib2HYv6od3FgR8MMKbryzSFIuXNV30Qn8=', 3, 17),
(24, 'Alizabet Acosta Montiel', 'economica@get.mrn.tur.cu', 1, 'tfEeRDizXh0uDEDxDWkOkaK6RzEo9sEAaCTth1RdPLo=', 2, 18),
(25, 'Eudelio Delgado Rojas', 'comercial@get.mrn.tur.cu', 1, 'KFGoRy4Dj+s4kTEc3USFoQ8lapzcuuncffVVFqQ7qCM=', 2, 18),
(26, 'Hector Perez Lorenzo', 'perez@get.mrn.tur.cu', 1, 'aqylRD7A7Xx62nCDSZ4+2wco6Pk6U1ug1lNxQqWkKB0=', 2, 23),
(27, 'Nelson Perez Torres', 'nelson@get.mrn.tur.cu', 1, 'J32otZMDPsWiFqKp57QkL85t4pnq1v1/smYfvC0GOGw=', 2, 15),
(28, 'Noidel Prado Amador', 'noidel.prado@get.mrn.tur.cu', 1, 'vB/QSUJdvB4RUDvBRDhTxanGrxG+3LbPxuyohPx8Pl4=', 2, 23),
(29, 'Karel Cepero Diaz', 'karel@get.mrn.tur.cu', 1, 'md9TIk8i0ttkmnaSLE0kBYYyNo3znRnq/eL726h96QI=', 2, 23);

-- 
-- Dumping data for table users_permissions
--
INSERT INTO users_permissions VALUES
(3, 5);

-- 
-- Dumping data for table analisis
--
INSERT INTO analisis VALUES
(1, 3, '5', '2016', 'Se cumplieron las tareas al 100% de forma satisfactoria'),
(2, 15, '6', '2016', 'Se cheque� en todas las reuniones de puntualizaci�n los lunes el estado de cumplimiento del plan de trabajo del mes, del plan de la econom�a y de la producci�n del mes, cumpli�ndose satisfactoriamente.'),
(3, 15, '8', '2016', 'Se cumpli� con el plan de la econom�a, se chequearon las tareas en las puntualizaciones y se cumpli� con los cronogramas de actualizaci�n previstos para el mes.'),
(4, 3, '8', '2016', 'Buen estado de cumplimiento de las tareas planificadas para el mes con un Cumplimiento del 100 %.'),
(5, NULL, '8', '2016', 'Se cumpli� satisfactoriamente el Plan de Econom�a, y se actualiz� el Sistema ZUNpr a la versi�n 1.0.3.3. Se detectaron varias irregularidades en el proceso de actualizaci�n as� como en su funcionamiento, se enviaron las deficiencias encontradas a GET Habana, Desarrollo, las cuales est�n en proceso de prueba y otras a�n no se han implementado. En general se cumple con las tareas planificadas en un 100%, y no existieron tareas extra planes ni pospuestas.'),
(6, 22, '7', '2016', 'Se cumple satisfactoriamente con el plan de econom�a y se actualiz� el Sistema ZUNpr, en el que se detectaron deficiencias y errores de concepto, �stos fueron enviados a desarrollo en GET Habana. No existieron tareas extra planes, ni suspendidas, por lo que se cumpli� con el Plan acordado.'),
(7, 22, '8', '2016', 'dvdf df'),
(8, 14, '8', '2016', 'Se cumplieron satisfactoriamente las tareas planificadas para el mes alcanzando un cumplimiento del 100 %.  Se prioriza la atenci�n al CAC para dar seguimiento a los reportes. Se mantiene limpieza y organizaci�n. Se cheque� en los matutinos los lunes el estado de cumplimiento del plan del plan de la econom�a y de la producci�n del mes, cumpli�ndose satisfactoriamente.');

-- 
-- Dumping data for table aprobacionpt
--
INSERT INTO aprobacionpt VALUES
(1, 3, 5, 2016),
(2, 3, 6, 2016),
(3, 17, 7, 2016),
(4, 3, 7, 2016),
(5, 15, 7, 2016),
(6, 21, 8, 2016),
(7, 21, 7, 2016),
(8, 22, 7, 2016),
(9, 17, 8, 2016),
(10, 15, 8, 2016),
(11, 3, 8, 2016),
(13, 22, 8, 2016),
(14, 17, 9, 2016),
(17, 15, 9, 2016),
(19, 3, 9, 2016);

-- 
-- Dumping data for table nuevas_tareas
--
INSERT INTO nuevas_tareas VALUES
(1, 3, 'Crear plan de trabajo para el forum', 'Necesidad de la empresa', 'No existe hoy en d�a un software automatizado para la creacion de los planes de trabajo', '5', '2016'),
(2, 15, 'Verificar entrega de parte Comercial', 'Amaury Basulto Sobrado', 'Necesidad de la Operaci�n', '10', '2016');

-- 
-- Dumping data for table predate
--
INSERT INTO predate VALUES
(1, 17, '2016-11-10', '15:00', '15:30', 'Hablar con evelio para que michel venda sus productos'),
(2, 3, '2016-10-12', '06:00', '06:30', 'testeando'),
(4, 17, '2016-10-12', '14:00', '14:00', 'Trabajo con tareas anuales'),
(5, 17, '2016-10-10', 'T/D', 'T/D', 'Dia de la rebeldia nacional');

-- 
-- Dumping data for table predefinida_fecha
--
INSERT INTO predefinida_fecha VALUES
(1, 'Elaboraci�n y envio de informaciones estad�sticas de RRHH', 5, '09:00', 16, NULL),
(2, 'Elaboraci�n y envio informaciones estad�sticas de Calidad', 5, '10:00', 16, NULL),
(3, 'Inventario del 10% de Almacen', 30, '10:00', 16, NULL),
(4, 'Elaboraci�n incidencias para el pago', 1, '08:00', 16, NULL),
(5, 'Realizaci�n Nomina de los Trabajadores', 1, '09:00', 14, NULL),
(6, 'Creacion y elaboracion del plan de trabajo.', 30, '14:00', 3, '14:15'),
(8, 'Consejo de Diereccion', 2, '10:00', 17, '10:30'),
(9, 'Autopreparacion', 8, '14:00', 15, '15:00');

-- 
-- Dumping data for table predefinidas
--
INSERT INTO predefinidas VALUES
(9, 'Atencion a reportes', 'Martes', 'T/D', 'T/D', 3, 2),
(10, 'Atencion a reportes', 'Mi�rcoles', 'T/D', 'T/D', 3, 3),
(11, 'Atencion a reportes', 'Jueves', 'T/D', NULL, 3, 4),
(12, 'Atencion a reportes', 'Viernes', 'T/D', 'T/D', 3, 5),
(15, 'Despacho c/ JB Softur', 'Lunes', '14:00', NULL, 22, 1),
(16, 'Auto-Preparaci�n', 'Lunes', '15:00', NULL, 22, 1),
(17, 'A/R', 'Lunes', '09:00', NULL, 22, 1),
(18, 'A/R', 'Martes', '08:00', NULL, 22, 2),
(19, 'A/R', 'Mi�rcoles', '08:00', NULL, 22, 3),
(20, 'A/R', 'Jueves', '08:00', NULL, 22, 4),
(21, 'A/R', 'Viernes', '08:00', NULL, 22, 5),
(22, 'Matutino', 'Lunes', '08:15', '08:40', 17, 1),
(23, 'Reuni�n de Puntualizaci�n', 'Lunes', '08:30', '09:00', 17, 1),
(24, 'Verificar entrega de parte Comercial', 'Jueves', '14:00', '14:00', 17, 4),
(25, 'Hacer Plan de Trabajo', 'Lunes', '08:00', NULL, 21, 1),
(26, 'Control energ�a y envio de informacion', 'Martes', '08:00', NULL, 27, 2),
(27, 'Control energ�a y envio de informacion', 'Lunes', '08:00', NULL, 27, 1),
(28, 'Control energ�a y envio de informacion', 'Mi�rcoles', '08:00', NULL, 27, 3),
(29, 'Control energ�a y envio de informacion', 'Jueves', '08:00', NULL, 27, 4),
(30, 'Control energ�a y envio de informacion', 'Viernes', '08:00', NULL, 27, 5),
(31, 'Matutino', 'Lunes', '08:15', NULL, 16, 1),
(32, 'Atenci�n al CAC', 'Lunes', '15:00', NULL, 16, 1),
(33, 'Atenci�n al CAC', 'Martes', '15:00', NULL, 16, 2),
(34, 'Atenci�n al CAC', 'Mi�rcoles', '15:00', NULL, 16, 3),
(35, 'Atenci�n al CAC', 'Jueves', '15:00', NULL, 16, 4),
(36, 'Atenci�n al CAC', 'Viernes', '15:00', NULL, 16, 5),
(37, 'Cuadre diario de Almacen', 'Lunes', '16:45', NULL, 16, 1),
(38, 'Cuadre diario de Almacen', 'Martes', '16:45', NULL, 16, 2),
(39, 'Despacho de mercancias', 'Lunes', '10:00', NULL, 16, 1),
(40, 'Despacho de mercancias', 'Martes', '11:00', NULL, 16, 2),
(41, 'Despacho de mercancias', 'Mi�rcoles', '11:00', NULL, 16, 3),
(42, 'Despacho de mercancias', 'Jueves', '11:00', NULL, 16, 4),
(43, 'Despacho de mercancias', 'Viernes', '10:00', NULL, 16, 5),
(44, 'Cuadre diario de Almacen', 'Mi�rcoles', '16:45', NULL, 16, 3),
(45, 'Cuadre diario de Almacen', 'Jueves', '16:45', NULL, 16, 4),
(46, 'Cuadre diario de Almacen', 'Viernes', '16:45', NULL, 16, 5),
(47, 'Matutino', 'Lunes', '08:15', NULL, 22, 1),
(48, 'Atenci�n a Reportes', 'Martes', 'T/D', NULL, 14, 2),
(49, 'Atenci�n a Reportes', 'Mi�rcoles', 'T/D', NULL, 14, 3),
(50, 'Atenci�n a Reportes', 'Jueves', 'T/D', NULL, 14, 4),
(51, 'Atenci�n a Reportes', 'Viernes', 'T/D', NULL, 14, 5),
(52, 'Atenci�n a Reportes', 'Lunes', '13:30', NULL, 14, 1),
(53, 'Matutino', 'Lunes', '08:15', NULL, 14, 1),
(54, 'Cuadre diario de almac�n', 'Lunes', '17:00', NULL, 18, 1),
(55, 'Cuadre diario de almac�n', 'Martes', '17:00', NULL, 18, 2),
(56, 'Cuadre diario de almac�n', 'Mi�rcoles', '17:00', NULL, 18, 3),
(57, 'Cuadre diario de almac�n', 'Jueves', '17:00', NULL, 18, 4),
(58, 'Cuadre diario de almac�n', 'Viernes', '17:00', NULL, 18, 5),
(59, 'Contabilizaci�n de operaciones diarias', 'Lunes', '10:00 am', NULL, 18, 1),
(60, 'Contabilizaci�n de operaciones diarias', 'Martes', '08:00 am', NULL, 18, 2),
(61, 'Contabilizaci�n de operaciones diarias', 'Mi�rcoles', '08:00 am', NULL, 18, 3),
(62, 'Contabilizaci�n de operaciones diarias', 'Jueves', '08:00 am', NULL, 18, 4),
(63, 'Contabilizaci�n de operaciones diarias', 'Viernes', '08:00 am', NULL, 18, 5),
(64, 'testeando', 'S�bado', 'T/D', 'T/D', 3, 6),
(67, 'testeando', 'Lunes', 'T/D', 'T/D', 3, 1);

-- 
-- Dumping data for table predefinidas_dias_fecha
--
INSERT INTO predefinidas_dias_fecha VALUES
(1, 'Asamblea de afiliados', 2, 'Lunes', '09:00', 3, 1, '09:30'),
(2, 'Consejo de Direccion UEB', 2, 'Lunes', '09:00', 17, 1, '09:30'),
(3, 'Despacho con JB Softur', 1, 'Lunes', '14:00', 17, 1, '14:30'),
(4, 'Despacho con JB AT&C+', 1, 'Lunes', '15:00', 17, 1, '15:15'),
(5, 'Comite de Prevencion y Control UEB', 3, 'Lunes', '14:00', 17, 1, '14:30'),
(6, 'Reunion del Nucleo del PCC', 2, 'Lunes', '15:00', 17, 1, '15:30'),
(7, 'Asamblea de Afiliados Sindical', 2, 'Lunes', '08:20', 14, 1, NULL),
(8, 'Consejo de direcci�n', 2, 'Lunes', '09:00', 18, 1, NULL),
(9, 'Asamblea de afiliados', 2, 'Lunes', '08:30', 18, 1, NULL),
(10, 'Autopreparaci�n', 4, 'Jueves', '02:00 Pm', 18, 4, NULL),
(11, 'Consejo de Diereccion', 2, 'Lunes', '10:00', 3, 1, '11:30');

-- 
-- Dumping data for table tareas_incumplidas
--

-- Table zunpt.tareas_incumplidas does not contain any data (it is empty)

-- 
-- Dumping data for table tareasprincipales
--
INSERT INTO tareasprincipales VALUES
(1, 3, 'Cumplimiento del plan de la econom', 6, 2016),
(2, 3, 'Consejo de direcci', 6, 2016),
(3, 3, 'Cumplimiento del plan de la economia', 7, 2016),
(4, 3, 'Terminar de programar el plan de trabajo.', 7, 2016),
(5, 17, 'Cumplimiento del Plan de la Economia de la UEB Julio 2016', 7, 2016),
(6, 17, 'Consejo de Direcci�n de la UEB', 7, 2016),
(7, 17, 'Consejo de Direcci�n Ampliado de GET', 7, 2016),
(8, 15, 'Cumplimiento del Plan de la Econom�a de la UEB', 7, 2016),
(9, 15, 'Consejo de Direcci�n de la UEB', 7, 2016),
(10, 15, 'Cumplimiento del Plan de la Econom�a de la UEB', 8, 2016),
(11, 27, 'Analisis de trazas', 8, 2016),
(12, 3, 'Cumplimiento del plan de la economia.', 8, 2016),
(13, 3, 'Consejo de Direccion UEB', 8, 2016),
(14, 22, 'Cumplir con el Plan de Econom�a.', 7, 2016),
(15, 22, 'Actualizaci�n de ZUNpr v 1.0.3.3', 7, 2016),
(16, 22, 'Cumplir con el Plan de Econom�a.', 8, 2016),
(17, 17, 'Cumplimiento del plan de la economia.', 10, 2016);

-- 
-- Dumping data for table vacaciones
--
INSERT INTO vacaciones VALUES
(1, 3, '2016-10-01', '2016-10-07'),
(2, 3, '2016-12-01', '2016-12-07'),
(3, 17, '2016-10-01', '2016-10-08');

-- 
-- Dumping data for table predate_subor
--
INSERT INTO predate_subor VALUES
(1, 4, 15),
(2, 4, 3),
(3, 5, 15),
(4, 5, 18),
(5, 5, 23),
(6, 5, 3),
(7, 5, 13),
(8, 5, 14),
(9, 5, 22),
(10, 5, 27),
(11, 5, 16),
(12, 5, 24),
(13, 5, 25),
(14, 5, 26),
(15, 5, 28),
(16, 5, 29);

-- 
-- Dumping data for table predefinida_fecha_subor
--
INSERT INTO predefinida_fecha_subor VALUES
(2, 8, 15),
(3, 8, 3),
(4, 9, 3);

-- 
-- Dumping data for table predefinidas_dias_fecha_subor
--
INSERT INTO predefinidas_dias_fecha_subor VALUES
(1, 2, 15),
(2, 2, 3),
(3, 6, 3),
(4, 2, 18),
(5, 2, 23),
(6, 2, 27);

-- 
-- Dumping data for table predefinidas_subor
--
INSERT INTO predefinidas_subor VALUES
(1, 54, 16),
(2, 55, 16),
(3, 56, 16),
(4, 57, 16),
(5, 58, 16),
(9, 22, 3),
(10, 22, 15),
(11, 23, 15),
(12, 23, 3);

-- 
-- Dumping data for table tareas_suspendidas
--

-- Table zunpt.tareas_suspendidas does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;