<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Mdl_participantes extends CI_Model
{

    public $table = 'participantes';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    function get_by_user_id($user_id,$grupo_id)
    {
        $this->db->where('users_id', $user_id);
        $this->db->where('grupo_participantes_id', $grupo_id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id', $q);
      //  $this->db->or_like('users_id', $q);
       // $this->db->or_like('grupo_participantes_id', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->select('participantes.id,users.name,grupo_participantes.titulo');
        $this->db->join('users','participantes.users_id = users.id','inner');
        $this->db->join('grupo_participantes','participantes.grupo_participantes_id = grupo_participantes.id','inner');
        $this->db->like('participantes.id', $q);

        $this->db->or_like('users.name', $q);
        $this->db->or_like('grupo_participantes.titulo', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
        return $this->db->insert_id();
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
        return $this->db->error();
    }

    function field_exists($field)
    {
        return $this->db->field_exists($field, $this->table);
    }

}

/* End of file Mdl_participantes.php */
/* Location: ./application/models/Mdl_participantes.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-03-21 16:05:11 */
/* http://harviacode.com */