<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Vacaciones_model extends CI_Model
{

    public $table = 'vacaciones';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL,$users_id) {
        $this->db->where('users_id',$users_id);
	    $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL,$users_id) {
        $this->db->order_by('desde', $this->order);
        $this->db->where('users_id',$users_id);
	    $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }
    function get_vacation($month,$year,$user_id)
    {

        $where =  "(MONTH(desde)='$month' AND YEAR(desde) = '$year' AND users_id = '$user_id')OR (MONTH(hasta)='$month' AND YEAR(desde) = '$year' AND users_id = '$user_id')";
        $this->db->where($where);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Vacaciones_model.php */
/* Location: ./application/models/Vacaciones_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-08-09 14:51:27 */
/* http://harviacode.com */