<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Predate_model extends CI_Model
{

    public $table = 'predate';
    public $id = 'id';
    public $order = 'ASC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL,$users_id)
    {
        $this->db->where('user_id',$users_id);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $users_id,$q = NULL)
    {
        $this->db->order_by("fecha", $this->order);
        $this->db->where('user_id',$users_id);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }
    function validaTarea($fecha, $hora_inicio,$hora_fin, $user_id)
    {
        $array = array('fecha'=>$fecha,'hora_inicio'=>$hora_inicio,'hora_fin'=>$hora_fin,'user_id'=>$user_id);
        $this->db->where($array);
        return $this->db->get($this->table)->result();
    }
    function get_actividades_month($month,$year,$user_id)
    {
        $array = array('month(fecha)'=>$month,'year(fecha)'=>$year,'user_id'=>$user_id);
        $this->db->where($array);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
    function get_max() {
        $this->db->select_max('id');
        $query = $this->db->get($this->table);
        $row=$query->row();
        $id=$row->id;
        return $id;
    }
    /* Trabajo con la tabla predate_subor */
    function insert_pre_sub($data)
    {
        $this->db->insert('predate_subor', $data);
    }
    // update data
    function update_pre_sub($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update('predate_subor', $data);
    }
    // delete data
    function delete_pre_sub($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete('predate_subor');
    }
    function get_pre_sub($id_pre)
    {
        $this->db->where('predate_id',$id_pre);
        return $this->db->get('predate_subor')->result();
    }
    function get_pre_subor_task($id_pre,$users_id)
    {
        $this->db->where('predate_id',$id_pre);
        $this->db->where('user_id',$users_id);
        return $this->db->get('predate_subor')->row();
    }
    function valida_pre_sub($id_pre,$users_id)
    {
        $this->db->where('predate_id',$id_pre);
        $this->db->where('user_id',$users_id);
        return $this->db->get('predate_subor')->result();
    }

    /************/


}

/* End of file Predate_model.php */
/* Location: ./application/models/Predate_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-09-22 16:22:05 */
/* http://harviacode.com */