<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Mdl_grupo_participantes extends CI_Model
{

    public $table = 'grupo_participantes';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    function get_by_flujo_id($flujo_id)
    {
        $this->db->select('*');
        $this->db->join('flujo_grupo','grupo_participantes.id = flujo_grupo.grupo_participantes_id','inner');
        $this->db->join('flujo_informativo','flujo_informativo.id = flujo_grupo.flujo_informativo_id','inner');
        $this->db->where('flujo_informativo.id',$flujo_id);
        return $this->db->get($this->table)->result();
    }

    function valida_data($data)
    {
        $this->db->where('titulo', $data);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id', $q);
        $this->db->or_like('titulo', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
        $this->db->or_like('titulo', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }
    function get_group_by_user($user_id)
    {
        $this->db->select('grupo_participantes.id,grupo_participantes.titulo');
        $this->db->join('participantes','grupo_participantes.id = participantes.grupo_participantes_id','inner');
        $this->db->where('participantes.users_id',$user_id);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
        return $this->db->insert_id();
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
        return $this->db->error();
    }

    function field_exists($field)
    {
        return $this->db->field_exists($field, $this->table);
    }

}

/* End of file Mdl_grupo_participantes.php */
/* Location: ./application/models/Mdl_grupo_participantes.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-03-21 16:03:52 */
/* http://harviacode.com */