<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Mdl_flujo_informativo extends CI_Model
{

    public $table = 'flujo_informativo';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('actividad', $q);
	$this->db->or_like('hora_inicio', $q);
	$this->db->or_like('hora_fin', $q);
	$this->db->or_like('dirigente', $q);
	$this->db->or_like('categoria_id', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('actividad', $q);
	$this->db->or_like('hora_inicio', $q);
	$this->db->or_like('hora_fin', $q);
	$this->db->or_like('dirigente', $q);
	$this->db->or_like('categoria_id', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
        return $this->db->insert_id();
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
        return $this->db->error();
    }

    function field_exists($field){
        return $this->db->field_exists($field, $this->table);
    }

}

/* End of file Mdl_flujo_informativo.php */
/* Location: ./application/models/Mdl_flujo_informativo.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-03-22 01:54:07 */
/* http://harviacode.com */