<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Predefinidas_dias_fecha_model extends CI_Model
{

    public $table = 'predefinidas_dias_fecha';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    function get_activity_by_user($user_id)
    {
        $this->db->where('users_id',$user_id);
        return $this->db->get($this->table)->result();
    }
    function verifica_tarea($data)
    {
        $array = array('cuando'=>$data['cuando'],'dia'=>$data['dia'],'hora'=>$data['hora'],'users_id'=>$data['users_id']);
        $this->db->where($array);
        return $this->db->get($this->table)->result();
    }
    function get_dia_hora($dia,$hora,$cuando,$user_id)
    {
        $array = array('dia'=>$dia,'hora'=>$hora,'cuando'=>$cuando,'users_id'=>$user_id);
        $this->db->where($array);
        return $this->db->get($this->table)->result();
    }
    function validaTarea($dia,$cuando, $hora,$hora_fin, $user_id)
    {
        $array = array('dia'=>$dia,'cuando'=>$cuando,'hora'=>$hora,'hora_fin'=>$hora_fin,'users_id'=>$user_id);
        $this->db->where($array);
        return $this->db->get($this->table)->result();
    }
    function get_dia($dia,$user_id,$cuando)
    {
        $array = array('dia'=>$dia,'users_id'=>$user_id, 'cuando'=>$cuando);
        $this->db->where($array);
        return $this->db->get($this->table)->result();
    }
    
    // get total rows
    function total_rows($q = NULL,$users_id) {
        $this->db->where('users_id',$users_id);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL,$users_id) {
        $this->db->order_by('orden', 'ASC');
        $this->db->like('tarea', $q);
        $this->db->where('users_id',$users_id);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    /* Trabajo con la tabla predefinidas_dias_fecha_subor */
    function insert_pre_sub($data)
    {
        $this->db->insert('predefinidas_dias_fecha_subor', $data);
    }
    // update data
    function update_pre_sub($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update('predefinidas_dias_fecha_subor', $data);
    }
    // delete data
    function delete_pre_sub($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete('predefinidas_dias_fecha_subor');
    }
    function delete_predef_subor($id_pre,$subor_id)
    {
        $this->db->where('predefinidas_dias_fecha_id',$id_pre);
        $this->db->where('user_id',$subor_id);
        $this->db->delete('predefinidas_dias_fecha_subor');
    }
    function get_pre_sub($id_pre,$subor_id)
    {
        $this->db->where('predefinidas_dias_fecha_id',$id_pre);
        $this->db->where('user_id',$subor_id);
        return $this->db->get('predefinidas_dias_fecha_subor')->result();
    }
    function get_pre_list_sub($id_pre)
    {
        $this->db->where('predefinidas_dias_fecha_id',$id_pre);
        return $this->db->get('predefinidas_dias_fecha_subor')->result();
    }
    function valida_pre_sub($id_pre,$users_id)
    {
        $this->db->where('predefinidas_dias_fecha_id',$id_pre);
        $this->db->where('user_id',$users_id);
        return $this->db->get('predefinidas_dias_fecha_subor')->result();
    }

    /************/

    function get_max() {
        $this->db->select_max('id');
        $query = $this->db->get($this->table);
        $row=$query->row();
        $id=$row->id;
        return $id;
    }

}

/* End of file Predefinidas_dias_fecha_model.php */
/* Location: ./application/models/Predefinidas_dias_fecha_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-07-12 23:07:00 */
/* http://harviacode.com */