<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tareasprincipales_model extends CI_Model
{

    public $table = 'tareasprincipales';
    public $id = 'id';
    public $order = 'ASC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($user_id,$month,$year)
    {

        $this->db->where('users_id', $user_id);
        $this->db->where('mes', $month);
        $this->db->where('ano', $year);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $user_id,$month,$year) {
        $this->db->order_by($this->id, $this->order);
        $this->db->where('users_id', $user_id);
        $this->db->where('mes', $month);
        $this->db->where('ano', $year);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }
    function get_prinipal_task($user_id,$month,$year) {
        $this->db->order_by($this->id, $this->order);
        $this->db->where('users_id', $user_id);
        $this->db->where('mes', $month);
        $this->db->where('ano', $year);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Tareasprincipales_model.php */
/* Location: ./application/models/Tareasprincipales_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-06-15 22:19:24 */
/* http://harviacode.com */