<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Predefinida_fecha_model extends CI_Model
{

    public $table = 'predefinida_fecha';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }
    function get_activity_by_user($user_id)
    {
        $this->db->where('users_id',$user_id);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    function get_dia_hora($dia,$hora,$user_id)
    {
        $array = array('dia'=>$dia,'hora'=>$hora,'users_id'=>$user_id);
        $this->db->where($array);
        return $this->db->get($this->table)->result();
    }
    function validaTarea($dia, $hora,$hora_fin, $user_id)
    {
        $array = array('dia'=>$dia,'hora'=>$hora,'hora_fin'=>$hora_fin,'users_id'=>$user_id);
        $this->db->where($array);
        return $this->db->get($this->table)->result();
    }
    function get_dia($dia,$user_id)
    {
        $array = array('dia'=>$dia,'users_id'=>$user_id);
        $this->db->where($array);
        return $this->db->get($this->table)->result();
    }
    
    // get total rows
    function total_rows($q = NULL,$users_id) {
        $this->db->where('users_id',$users_id);

        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL,$users_id) {
        $this->db->order_by('dia', $this->order);
        $this->db->like('tarea', $q);
        $this->db->where('users_id',$users_id);

        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    /* Trabajo con la tabla predefinida_fecha_subor */
    function insert_pre_sub($data)
    {
        $this->db->insert('predefinida_fecha_subor', $data);
    }
    // update data
    function update_pre_sub($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update('predefinida_fecha_subor', $data);
    }
    // delete data
    function delete_pre_sub($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete('predefinida_fecha_subor');
    }
    function delete_predefinida_subordinado($predefinida_fecha_id,$subor_id)
    {
        $this->db->where('predefinida_fecha_id',$predefinida_fecha_id);
        $this->db->where('user_id', $subor_id);
        $this->db->delete('predefinida_fecha_subor');
    }
    function get_pre_sub($id_pre,$subor_id) //devuelve los usuarios subordinados con las mismas tareas del jefe
    {
        $this->db->where('predefinida_fecha_id',$id_pre);
        $this->db->where('user_id',$subor_id);
        return $this->db->get('predefinida_fecha_subor')->result();
    }
    function valida_pre_sub($id_pre,$users_id)
    {
        $this->db->where('predefinida_fecha_id',$id_pre);
        $this->db->where('user_id',$users_id);
        return $this->db->get('predefinida_fecha_subor')->result();
    }
    function get_list_pre_sub($id_pre) //devuelve los usuarios subordinados con las mismas tareas del jefe
    {
        $this->db->where('predefinida_fecha_id',$id_pre);
        return $this->db->get('predefinida_fecha_subor')->result();
    }
    /******************/
    function get_max() {
        $this->db->select_max('id');
        $query = $this->db->get($this->table);
        $row=$query->row();
        $id=$row->id;
        return $id;
    }


}

/* End of file Predefinida_fecha_model.php */
/* Location: ./application/models/Predefinida_fecha_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-07-11 12:25:35 */
/* http://harviacode.com */